import "./globals.css";
import Navigation from "../components/Navigation";

export const metadata = {
  title: "Demo NextJS App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-lavender text-white">
        <Navigation />
        {children}
        <footer className="text-light text-center">
          <div className="p-4">
            <h1 className="text-light">&copy; All rights reserved</h1>
            <p>{new Date().getFullYear()}</p>
          </div>
        </footer>
      </body>
    </html>
  );
}
